更新java版本，增加注释，更新mirai版本
project-mirai/mirai-console-plugin-template pull request #8
Opened 2021-06-19 03:30 UTC by Nambers

2021-06-19 08:09 UTC, Karlatemp requested changes

2021-06-19 08:09 UTC, Karlatemp commented on build.gradle.kts
>  }
2.6.x 的 mirai 使用的 kotlin 版本为 1.4.30

2021-06-19 08:09 UTC, Karlatemp commented on src/main/java/org/example/mirai/plugin/JavaPluginMain.java
> + */
```suggestion
/**
 * 使用 java 请把
 * {@code /src/main/resources/META-INF.services/net.mamoe.mirai.console.plugin.jvm.JvmPlugin}
 * 文件内容改成 {@code org.example.mirai.plugin.JavaPluginMain} <br/>
 * 也就是当前主类全类名
 *
 * 使用 java 可以把 kotlin 源集删除且不会对项目有影响
 *
 * 在 {@code settings.gradle.kts} 里改构建的插件名称、依赖库和插件版本
 *
 * 在该示例下的 {@link JvmPluginDescription} 修改插件名称，id和版本，etc
 *
 * 可以使用 {@code src/test/kotlin/RunMirai.kt} 在 ide 里直接调试，
 * 不用复制到 mirai-console-loader 或其他启动器中调试
 */
```

2021-06-19 08:09 UTC, Karlatemp commented on src/main/java/org/example/mirai/plugin/JavaPluginMain.java
> +        GlobalEventChannel.INSTANCE.subscribeAlways(GroupMessageEvent.class, g -> {
最好使用插件专属的 eventChannel

2021-06-19 08:09 UTC, Karlatemp commented on src/main/kotlin/PluginMain.kt
> + */
```suggestion
/**
 * 使用 kotlin 版请把
 * `src/main/resources/META-INF.services/net.mamoe.mirai.console.plugin.jvm.JvmPlugin`
 * 文件内容改成 `org.example.mirai.plugin.PluginMain` 也就是当前主类全类名
 *
 * 使用 kotlin 可以把 java 源集删除不会对项目有影响
 *
 * 在 `settings.gradle.kts` 里改构建的插件名称、依赖库和插件版本
 *
 * 在该示例下的 [JvmPluginDescription] 修改插件名称，id和版本，etc
 *
 * 可以使用 `src/test/kotlin/RunMirai.kt` 在 ide 里直接调试，
 * 不用复制到 mirai-console-loader 或其他启动器中调试
 */
```

2021-06-19 08:39 UTC, Nambers commented on build.gradle.kts
>  }
ok 我改成1.4.30

2021-06-19 08:40 UTC, Nambers commented on src/main/java/org/example/mirai/plugin/JavaPluginMain.java
> +        GlobalEventChannel.INSTANCE.subscribeAlways(GroupMessageEvent.class, g -> {
是指在插件中创建一个EventChannel吗

2021-06-19 09:09 UTC, Karlatemp approved these changes

2021-06-19 09:19 UTC, Him188 requested changes

2021-06-19 09:19 UTC, Him188 commented on src/main/java/org/example/mirai/plugin/JavaPluginMain.java
> + * 使用 java 可以把 kotlin 源集删除且不会对项目有影响
```suggestion
 * 使用 Java 可以把 kotlin 源集删除且不会对项目有影响
```

2021-06-19 09:19 UTC, Him188 commented on src/main/java/org/example/mirai/plugin/JavaPluginMain.java
> + * 使用 java 请把
```suggestion
 * 使用 Java 请把
```

2021-06-19 09:19 UTC, Him188 commented on src/main/java/org/example/mirai/plugin/JavaPluginMain.java
> + * 可以使用 {@code src/test/kotlin/RunMirai.kt} 在 ide 里直接调试，
```suggestion
 * 可以使用 {@code src/test/kotlin/RunMirai.kt} 在 IDE 里直接调试，
```

2021-06-19 09:19 UTC, Him188 commented on src/main/java/org/example/mirai/plugin/JavaPluginMain.java
> + * 在该示例下的 {@link JvmPluginDescription} 修改插件名称，id和版本，etc
```suggestion
 * 在该示例下的 {@link JvmPluginDescription} 修改插件名称，id 和版本等
```

2021-06-25 09:39 UTC, Him188 approved these changes

2021-06-25 09:40 UTC, Him188 commented
~其实我都忘了有这个事情~ GitHub 没有待办

2021-06-25 09:47 UTC, Karlatemp commented
屑

2021-06-25 10:02 UTC, merged